// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanWithOptions(arg1) {
  return window['go']['main']['App']['CleanWithOptions'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CrawlPapers(arg1, arg2) {
  return window['go']['main']['App']['CrawlPapers'](arg1, arg2);
}

export function ExportSelection(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ExportSelection'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExportSelectionByPapers(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExportSelectionByPapers'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportWithOptions(arg1) {
  return window['go']['main']['App']['ExportWithOptions'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCrawlTask(arg1) {
  return window['go']['main']['App']['GetCrawlTask'](arg1);
}

export function GetCrawlTaskLogs(arg1) {
  return window['go']['main']['App']['GetCrawlTaskLogs'](arg1);
}

export function GetDailyRecommendations(arg1) {
  return window['go']['main']['App']['GetDailyRecommendations'](arg1);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPapers(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPapers'](arg1, arg2, arg3, arg4);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function SearchWithOptions(arg1) {
  return window['go']['main']['App']['SearchWithOptions'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
