// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function AnalyzeSearchQuery(arg1:string):Promise<string>;

export function CleanWithOptions(arg1:main.CleanOptions):Promise<main.CleanResult>;

export function ClearLogs():Promise<void>;

export function CrawlPapers(arg1:string,arg2:Record<string, any>):Promise<string>;

export function DebugRecommendationInfo():Promise<string>;

export function ExportSelection(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:string,arg6:string):Promise<string>;

export function ExportSelectionByPapers(arg1:string,arg2:Array<Record<string, string>>,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ExportWithOptions(arg1:main.ExportOptions):Promise<string>;

export function GetConfig():Promise<config.AppConfig>;

export function GetCrawlTask(arg1:string):Promise<string>;

export function GetCrawlTaskLogs(arg1:string):Promise<string>;

export function GetDailyRecommendations(arg1:main.RecommendOptions):Promise<string>;

export function GetLogs():Promise<string>;

export function GetPapers(arg1:number,arg2:number,arg3:string,arg4:string):Promise<main.PaperListResponse>;

export function GetSearchContext():Promise<string>;

export function ReloadConfig():Promise<void>;

export function SearchWithOptions(arg1:main.SearchOptions):Promise<string>;

export function SetLogLevel(arg1:string):Promise<void>;

export function UpdateConfig(arg1:config.AppConfig):Promise<void>;
